// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqop6gk7hR58r0eEesp58N4HTUFQMTO8',
    appId: '1:1096420113105:web:5d0663afd2d929165ce3f0',
    messagingSenderId: '1096420113105',
    projectId: 'dira-clinicops',
    authDomain: 'dira-clinicops.firebaseapp.com',
    storageBucket: 'dira-clinicops.firebasestorage.app',
    measurementId: 'G-2KJXFZ8VXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKC1c2JTEJXCgXLN4vMesgxGaw8HfF8cI',
    appId: '1:1096420113105:android:422b339beab4397e5ce3f0',
    messagingSenderId: '1096420113105',
    projectId: 'dira-clinicops',
    storageBucket: 'dira-clinicops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfDFUHLfEzW-fBUHBlXAj3qBge3rxo6Ns',
    appId: '1:1096420113105:ios:4fd5ee275211b00a5ce3f0',
    messagingSenderId: '1096420113105',
    projectId: 'dira-clinicops',
    storageBucket: 'dira-clinicops.firebasestorage.app',
    iosBundleId: 'com.example.dira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfDFUHLfEzW-fBUHBlXAj3qBge3rxo6Ns',
    appId: '1:1096420113105:ios:4fd5ee275211b00a5ce3f0',
    messagingSenderId: '1096420113105',
    projectId: 'dira-clinicops',
    storageBucket: 'dira-clinicops.firebasestorage.app',
    iosBundleId: 'com.example.dira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqop6gk7hR58r0eEesp58N4HTUFQMTO8',
    appId: '1:1096420113105:web:1732dfa51e129d375ce3f0',
    messagingSenderId: '1096420113105',
    projectId: 'dira-clinicops',
    authDomain: 'dira-clinicops.firebaseapp.com',
    storageBucket: 'dira-clinicops.firebasestorage.app',
    measurementId: 'G-GFNZ1VZB6H',
  );
}
